export const NLP_SEARCH_EXAMPLES: string[] = [
  "People with chronic kidney disease stage 3–5",
  "People with CKD",
  "People with Chronic Kidney Disease",
  "People with Renal Failure",
  "Obese adults",
  "Adults with obesity",
  "Children with COPD",
  "People with stroke recorded in the last 5 years",
  "People with schizophrenia",
  "Adults with bipolar disorder",
  "People with dementia diagnosis",
  "People with inflammatory bowel disease",
  "People with Crohn's disease",
  "People with ulcerative colitis",
  "People with cancer over the age of 50 who have been treated for hip fractures",
  "Men over 60 with cancer in NHS Scotland Regions",
  "Individuals who have antibodies to SARS-CoV-2 measured after receiving two doses of any COVID-19 vaccine",
  "Black men over the age of 60 who have had heart attacks while being on blood thinners",
  "People with asthma who have had oral steroid courses in the last 12 months",
  "Adults with COPD who started home oxygen therapy in the last 2 years",
  "People with atrial fibrillation who have had an ischaemic stroke despite being prescribed anticoagulation",
  "Women with polycystic ovary syndrome who later developed type 2 diabetes",
  "Pregnant women with gestational diabetes who delivered preterm",
  "People with osteoarthritis who received a knee replacement and had a postoperative infection within 90 days",
  "Adults with severe obesity who underwent bariatric surgery and had type 2 diabetes remission within 12 months",
];
