name: Build and deploy to DEV
run-name:  ${{ github.actor }} triggered deploy to DEV pipeline

on:
  push:
    branches:
      - dev

jobs:
  setup-standalone:
    uses: ./.github/workflows/build-args.yaml
    with:
      environment: dev-standalone
      mode: standalone

  build-standalone:
    needs: setup-standalone
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/cohort-web/Chart.yaml
      environment: dev-standalone
      docker_build_args: ${{ needs.setup-standalone.outputs.docker_build_args }}
    secrets: inherit

  deploy-standalone:
    needs: build-standalone
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev-standalone
      chart_path: chart/cohort-web/Chart.yaml
      git_ref: dev
    secrets: inherit

  setup-integrated:
    uses: ./.github/workflows/build-args.yaml
    with:
      environment: dev-integrated
      mode: integrated

  build-integrated:
    needs: setup-integrated
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/cohort-web/Chart.yaml
      environment: dev-integrated
      docker_build_args: ${{ needs.setup-integrated.outputs.docker_build_args }}
    secrets: inherit

  deploy-integrated:
    needs: build-integrated
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev-integrated
      chart_path: chart/cohort-web/Chart.yaml
      git_ref: dev
    secrets: inherit