name: Semantic Release workflow

on:
  push:
    branches:
      - main

jobs:
  semantic:
    uses: HDRUK/github-actions-templates/.github/workflows/semantic.yaml@main
    with:
      chart_path: chart/cohort-web/Chart.yaml
    secrets: inherit

  setup-preprod:
    uses: ./.github/workflows/build-args.yaml
    with:
      environment: preprod
      mode: standalone

  build-preprod:
    needs: setup-preprod
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/cohort-web/Chart.yaml
      environment: preprod
      docker_build_args: ${{ needs.setup-preprod.outputs.docker_build_args }}
    secrets: inherit

  setup-prod:
    uses: ./.github/workflows/build-args.yaml
    with:
      environment: prod
      mode: standalone

  build-prod:
    needs: setup-prod
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/cohort-web/Chart.yaml
      environment: prod
      docker_build_args: ${{ needs.setup-prod.outputs.docker_build_args }}
    secrets: inherit